{
  "output": {
    "c__application_client_id": {
      "value": "${azuread_application.prisma_cloud_app.application_id}"
    },
    "e__enterprise_application_object_id": {
      "value": "${azuread_service_principal.prisma_cloud_sp.id}"
    },
    "d__application_client_secret": {
      "value": "${nonsensitive(azuread_application_password.password.value)}"
    },
    "b__subscription_id": {
      "value": "${var.subscription_id}"
    },
    "a__directory_tenant_id": {
      "value": "${var.tenant_id}"
    }
  },
  "provider": {
    "random": {},
    "azuread": {
      "tenant_id": "${var.tenant_id}",
      "environment": "${var.cloud_environment}"
    },
    "time": {},
    "azurerm": {
      "tenant_id": "${var.tenant_id}",
      "subscription_id": "${var.subscription_id}",
      "features": {}
    }
  },
  "resource": {
    "azuread_application_password": {
      "password": {
        "application_object_id": "${azuread_application.prisma_cloud_app.object_id}",
        "end_date_relative": "${var.application_password_expiration}"
      }
    },
    "random_string": {
      "unique_id": {
        "special": false,
        "length": 5,
        "min_lower": 5
      }
    },
    "azuread_service_principal": {
      "prisma_cloud_sp": {
        "application_id": "${azuread_application.prisma_cloud_app.application_id}"
      }
    },
    "time_sleep": {
      "wait_20_seconds": {
        "depends_on": [
          "azurerm_role_definition.custom_prisma_role"
        ],
        "create_duration": "20s"
      }
    },
    "azuread_application": {
      "prisma_cloud_app": {
        "web": {
          "homepage_url": "https://www.paloaltonetworks.com/prisma/cloud"
        },
        "display_name": "Prisma Cloud App ${random_string.unique_id.result}"
      }
    },
    "random_password": {
      "application_password": {
        "special": true,
        "length": 32
      }
    },
    "azurerm_role_assignment": {
      "assign_builtin_roles": {
        "skip_service_principal_aad_check": true,
        "scope": "/subscriptions/${var.subscription_id}",
        "for_each": "${toset(var.builtin_roles)}",
        "role_definition_name": "${each.key}",
        "principal_id": "${azuread_service_principal.prisma_cloud_sp.id}"
      },
      "assign_custom_prisma_role": {
        "role_definition_id": "${azurerm_role_definition.custom_prisma_role.role_definition_resource_id}",
        "depends_on": [
          "time_sleep.wait_20_seconds"
        ],
        "skip_service_principal_aad_check": true,
        "scope": "/subscriptions/${var.subscription_id}",
        "principal_id": "${azuread_service_principal.prisma_cloud_sp.id}"
      }
    },
    "azurerm_role_definition": {
      "custom_prisma_role": {
        "assignable_scopes": [
          "/subscriptions/${var.subscription_id}"
        ],
        "permissions": {
          "actions": "${var.custom_role_actions}",
          "not_actions": []
        },
        "scope": "/subscriptions/${var.subscription_id}",
        "name": "Prisma Cloud ${random_string.unique_id.result}",
        "timeouts": {
          "read": "5m",
          "create": "5m"
        },
        "description": "Prisma Cloud custom role created via Terraform"
      }
    }
  },
  "variable": {
    "tenant_id": {
      "default": "1f12db8a-1b27-441c-a372-d7e41375cc13",
      "type": "string"
    },
    "subscription_id": {
      "default": "1f12db8a-1b27-441c-a372-d7e41375cc13",
      "type": "string"
    },
    "builtin_roles": {
      "default": [
        "Reader"
      ],
      "type": "list"
    },
    "custom_role_actions": {
      "default": [
        "Microsoft.Advisor/configurations/read",
        "Microsoft.AnalysisServices/servers/read",
        "Microsoft.ApiManagement/service/portalsettings/read",
        "Microsoft.ApiManagement/service/read",
        "Microsoft.ApiManagement/service/tenant/read",
        "Microsoft.AppConfiguration/configurationStores/read",
        "Microsoft.AppPlatform/Spring/apps/read",
        "Microsoft.AppPlatform/Spring/read",
        "Microsoft.Attestation/attestationProviders/read",
        "Microsoft.Authorization/classicAdministrators/read",
        "Microsoft.Authorization/locks/read",
        "Microsoft.Authorization/permissions/read",
        "Microsoft.Authorization/policyAssignments/read",
        "Microsoft.Authorization/policyDefinitions/read",
        "Microsoft.Authorization/roleAssignments/read",
        "Microsoft.Authorization/roleDefinitions/read",
        "Microsoft.Automanage/configurationProfiles/Read",
        "Microsoft.Automation/automationAccounts/read",
        "Microsoft.Automation/automationAccounts/variables/read",
        "Microsoft.AzureStackHCI/Clusters/Read",
        "Microsoft.Batch/batchAccounts/pools/read",
        "Microsoft.Batch/batchAccounts/read",
        "Microsoft.Blueprint/blueprints/read",
        "Microsoft.BotService/botServices/read",
        "Microsoft.Cache/redis/firewallRules/read",
        "Microsoft.Cache/redis/read",
        "Microsoft.Cdn/profiles/endpoints/customdomains/read",
        "Microsoft.Cdn/profiles/endpoints/read",
        "Microsoft.Cdn/profiles/origingroups/read",
        "Microsoft.Cdn/profiles/read",
        "Microsoft.Cdn/profiles/securitypolicies/read",
        "Microsoft.Chaos/experiments/read",
        "Microsoft.ClassicCompute/VirtualMachines/read",
        "Microsoft.ClassicNetwork/networkSecurityGroups/read",
        "Microsoft.ClassicNetwork/reservedIps/read",
        "Microsoft.ClassicNetwork/virtualNetworks/read",
        "Microsoft.ClassicStorage/StorageAccounts/read",
        "Microsoft.CognitiveServices/accounts/read",
        "Microsoft.Communication/CommunicationServices/Read",
        "Microsoft.Compute/availabilitySets/read",
        "Microsoft.Compute/cloudServices/read",
        "Microsoft.Compute/cloudServices/roleInstances/read",
        "Microsoft.Compute/disks/beginGetAccess/action",
        "Microsoft.Compute/disks/delete",
        "Microsoft.Compute/disks/read",
        "Microsoft.Compute/disks/write",
        "Microsoft.Compute/galleries/images/read",
        "Microsoft.Compute/galleries/read",
        "Microsoft.Compute/hostGroups/read",
        "Microsoft.Compute/snapshots/delete",
        "Microsoft.Compute/snapshots/read",
        "Microsoft.Compute/snapshots/write",
        "Microsoft.Compute/virtualMachineScaleSets/networkInterfaces/read",
        "Microsoft.Compute/virtualMachineScaleSets/publicIPAddresses/read",
        "Microsoft.Compute/virtualMachineScaleSets/read",
        "Microsoft.Compute/virtualMachineScaleSets/virtualMachines/networkInterfaces/ipConfigurations/publicIPAddresses/read",
        "Microsoft.Compute/virtualMachineScaleSets/virtualMachines/read",
        "Microsoft.Compute/virtualMachineScaleSets/virtualmachines/instanceView/read",
        "Microsoft.Compute/virtualMachines/delete",
        "Microsoft.Compute/virtualMachines/extensions/read",
        "Microsoft.Compute/virtualMachines/instanceView/read",
        "Microsoft.Compute/virtualMachines/read",
        "Microsoft.Compute/virtualMachines/write",
        "Microsoft.Confluent/organizations/Read",
        "Microsoft.ContainerInstance/containerGroups/containers/exec/action",
        "Microsoft.ContainerInstance/containerGroups/read",
        "Microsoft.ContainerRegistry/registries/metadata/read",
        "Microsoft.ContainerRegistry/registries/pull/read",
        "Microsoft.ContainerRegistry/registries/read",
        "Microsoft.ContainerRegistry/registries/webhooks/getCallbackConfig/action",
        "Microsoft.ContainerService/managedClusters/read",
        "Microsoft.DBforMariaDB/servers/read",
        "Microsoft.DBforMySQL/flexibleServers/configurations/read",
        "Microsoft.DBforMySQL/flexibleServers/firewallRules/read",
        "Microsoft.DBforMySQL/flexibleServers/read",
        "Microsoft.DBforMySQL/servers/firewallRules/read",
        "Microsoft.DBforMySQL/servers/read",
        "Microsoft.DBforMySQL/servers/virtualNetworkRules/read",
        "Microsoft.DBforPostgreSQL/flexibleServers/configurations/read",
        "Microsoft.DBforPostgreSQL/flexibleServers/firewallRules/read",
        "Microsoft.DBforPostgreSQL/flexibleServers/read",
        "Microsoft.DBforPostgreSQL/servers/configurations/read",
        "Microsoft.DBforPostgreSQL/servers/firewallRules/read",
        "Microsoft.DBforPostgreSQL/servers/read",
        "Microsoft.DBforPostgreSQL/serversv2/firewallRules/read",
        "Microsoft.Dashboard/grafana/read",
        "Microsoft.DataBoxEdge/dataBoxEdgeDevices/read",
        "Microsoft.DataCatalog/catalogs/read",
        "Microsoft.DataFactory/datafactories/read",
        "Microsoft.DataFactory/factories/read",
        "Microsoft.DataLakeAnalytics/accounts/dataLakeStoreAccounts/read",
        "Microsoft.DataLakeAnalytics/accounts/firewallRules/read",
        "Microsoft.DataLakeAnalytics/accounts/read",
        "Microsoft.DataLakeAnalytics/accounts/storageAccounts/read",
        "Microsoft.DataLakeStore/accounts/firewallRules/read",
        "Microsoft.DataLakeStore/accounts/read",
        "Microsoft.DataLakeStore/accounts/trustedIdProviders/read",
        "Microsoft.DataLakeStore/accounts/virtualNetworkRules/read",
        "Microsoft.DataMigration/services/read",
        "Microsoft.DataShare/accounts/read",
        "Microsoft.Databricks/workspaces/read",
        "Microsoft.Datadog/monitors/read",
        "Microsoft.DesktopVirtualization/hostpools/read",
        "Microsoft.DesktopVirtualization/hostpools/sessionhostconfigurations/read",
        "Microsoft.DesktopVirtualization/hostpools/sessionhosts/read",
        "Microsoft.DesktopVirtualization/workspaces/providers/Microsoft.Insights/diagnosticSettings/read",
        "Microsoft.DesktopVirtualization/workspaces/read",
        "Microsoft.DevCenter/devcenters/read",
        "Microsoft.DevTestLab/schedules/read",
        "Microsoft.Devices/iotHubs/Read",
        "Microsoft.Devices/iotHubs/privateLinkResources/Read",
        "Microsoft.DigitalTwins/digitalTwinsInstances/read",
        "Microsoft.DocumentDB/cassandraClusters/read",
        "Microsoft.DocumentDB/databaseAccounts/read",
        "Microsoft.DomainRegistration/domains/Read",
        "Microsoft.Easm/workspaces/read",
        "Microsoft.Elastic/monitors/read",
        "Microsoft.EventGrid/domains/privateLinkResources/read",
        "Microsoft.EventGrid/domains/read",
        "Microsoft.EventGrid/topics/privateLinkResources/read",
        "Microsoft.EventGrid/topics/read",
        "Microsoft.EventHub/Namespaces/PrivateEndpointConnections/read",
        "Microsoft.EventHub/clusters/read",
        "Microsoft.EventHub/namespaces/authorizationRules/read",
        "Microsoft.EventHub/namespaces/eventhubs/authorizationRules/read",
        "Microsoft.EventHub/namespaces/eventhubs/read",
        "Microsoft.EventHub/namespaces/ipfilterrules/read",
        "Microsoft.EventHub/namespaces/read",
        "Microsoft.EventHub/namespaces/virtualnetworkrules/read",
        "Microsoft.HDInsight/clusters/applications/read",
        "Microsoft.HDInsight/clusters/read",
        "Microsoft.HealthBot/healthBots/Read",
        "Microsoft.HealthcareApis/workspaces/read",
        "Microsoft.HybridCompute/machines/read",
        "Microsoft.Insights/ActivityLogAlerts/read",
        "Microsoft.Insights/Components/read",
        "Microsoft.Insights/LogProfiles/read",
        "Microsoft.Insights/actionGroups/read",
        "Microsoft.Insights/diagnosticSettings/read",
        "Microsoft.Insights/eventtypes/values/read",
        "Microsoft.IoTCentral/IoTApps/read",
        "Microsoft.KeyVault/vaults/keys/read",
        "Microsoft.KeyVault/vaults/privateLinkResources/read",
        "Microsoft.KeyVault/vaults/read",
        "Microsoft.Kusto/Clusters/read",
        "Microsoft.LabServices/labs/read",
        "Microsoft.LoadTestService/loadTests/read",
        "Microsoft.Logic/integrationAccounts/read",
        "Microsoft.Logic/workflows/read",
        "Microsoft.MachineLearning/commitmentPlans/read",
        "Microsoft.MachineLearning/webServices/read",
        "Microsoft.MachineLearning/workspaces/read",
        "Microsoft.MachineLearningServices/workspaces/read",
        "Microsoft.ManagedIdentity/userAssignedIdentities/read",
        "Microsoft.ManagedServices/marketplaceRegistrationDefinitions/read",
        "Microsoft.ManagedServices/registrationAssignments/read",
        "Microsoft.Management/managementGroups/descendants/read",
        "Microsoft.Management/managementGroups/read",
        "Microsoft.Management/managementGroups/subscriptions/read",
        "Microsoft.Maps/accounts/read",
        "Microsoft.Media/mediaservices/read",
        "Microsoft.Migrate/moveCollections/read",
        "Microsoft.MixedReality/ObjectAnchorsAccounts/read",
        "Microsoft.NetApp/netAppAccounts/read",
        "Microsoft.Network/ApplicationGatewayWebApplicationFirewallPolicies/read",
        "Microsoft.Network/applicationGateways/read",
        "Microsoft.Network/applicationSecurityGroups/read",
        "Microsoft.Network/azurefirewalls/read",
        "Microsoft.Network/bastionHosts/read",
        "Microsoft.Network/connections/read",
        "Microsoft.Network/ddosProtectionPlans/read",
        "Microsoft.Network/dnsZones/read",
        "Microsoft.Network/expressRouteCircuits/authorizations/read",
        "Microsoft.Network/expressRouteCircuits/peerings/connections/read",
        "Microsoft.Network/expressRouteCircuits/peerings/peerConnections/read",
        "Microsoft.Network/expressRouteCircuits/peerings/read",
        "Microsoft.Network/expressRouteCircuits/read",
        "Microsoft.Network/expressRouteCrossConnections/peerings/read",
        "Microsoft.Network/expressRouteCrossConnections/read",
        "Microsoft.Network/expressRouteGateways/expressRouteConnections/read",
        "Microsoft.Network/expressRouteGateways/read",
        "Microsoft.Network/expressRoutePorts/authorizations/read",
        "Microsoft.Network/expressRoutePorts/links/read",
        "Microsoft.Network/expressRoutePorts/read",
        "Microsoft.Network/expressRoutePortsLocations/read",
        "Microsoft.Network/firewallPolicies/read",
        "Microsoft.Network/frontDoorWebApplicationFirewallPolicies/read",
        "Microsoft.Network/frontDoors/backendPools/read",
        "Microsoft.Network/frontDoors/frontendEndpoints/read",
        "Microsoft.Network/frontDoors/healthProbeSettings/read",
        "Microsoft.Network/frontDoors/loadBalancingSettings/read",
        "Microsoft.Network/frontDoors/read",
        "Microsoft.Network/frontDoors/routingRules/read",
        "Microsoft.Network/frontDoors/rulesEngines/read",
        "Microsoft.Network/loadBalancers/read",
        "Microsoft.Network/localnetworkgateways/read",
        "Microsoft.Network/locations/usages/read",
        "Microsoft.Network/natGateways/read",
        "Microsoft.Network/networkInterfaces/delete",
        "Microsoft.Network/networkInterfaces/effectiveNetworkSecurityGroups/action",
        "Microsoft.Network/networkInterfaces/effectiveRouteTable/action",
        "Microsoft.Network/networkInterfaces/join/action",
        "Microsoft.Network/networkInterfaces/read",
        "Microsoft.Network/networkInterfaces/write",
        "Microsoft.Network/networkSecurityGroups/defaultSecurityRules/read",
        "Microsoft.Network/networkSecurityGroups/delete",
        "Microsoft.Network/networkSecurityGroups/join/action",
        "Microsoft.Network/networkSecurityGroups/read",
        "Microsoft.Network/networkSecurityGroups/securityRules/read",
        "Microsoft.Network/networkSecurityGroups/write",
        "Microsoft.Network/networkWatchers/queryFlowLogStatus/*",
        "Microsoft.Network/networkWatchers/read",
        "Microsoft.Network/networkWatchers/securityGroupView/action",
        "Microsoft.Network/p2sVpnGateways/read",
        "Microsoft.Network/privateEndpoints/read",
        "Microsoft.Network/privateLinkServices/read",
        "Microsoft.Network/publicIPAddresses/read",
        "Microsoft.Network/publicIPPrefixes/read",
        "Microsoft.Network/routeFilters/read",
        "Microsoft.Network/routeFilters/routeFilterRules/read",
        "Microsoft.Network/routeTables/read",
        "Microsoft.Network/routeTables/routes/read",
        "Microsoft.Network/serviceEndpointPolicies/read",
        "Microsoft.Network/serviceEndpointPolicies/serviceEndpointPolicyDefinitions/read",
        "Microsoft.Network/trafficManagerProfiles/read",
        "Microsoft.Network/virtualNetworkGateways/read",
        "Microsoft.Network/virtualNetworks/delete",
        "Microsoft.Network/virtualNetworks/read",
        "Microsoft.Network/virtualNetworks/subnets/join/action",
        "Microsoft.Network/virtualNetworks/subnets/read",
        "Microsoft.Network/virtualNetworks/virtualNetworkPeerings/read",
        "Microsoft.Network/virtualNetworks/write",
        "Microsoft.Network/virtualWans/read",
        "Microsoft.Network/virtualwans/vpnconfiguration/action",
        "Microsoft.Network/vpnServerConfigurations/read",
        "Microsoft.NetworkFunction/azureTrafficCollectors/read",
        "Microsoft.NotificationHubs/Namespaces/NotificationHubs/read",
        "Microsoft.NotificationHubs/Namespaces/read",
        "Microsoft.OperationalInsights/workspaces/read",
        "Microsoft.Orbital/spacecrafts/read",
        "Microsoft.PowerBIDedicated/capacities/read",
        "Microsoft.PowerBIDedicated/servers/read",
        "Microsoft.Quantum/Workspaces/Read",
        "Microsoft.RecoveryServices/Vaults/backupProtectedItems/read",
        "Microsoft.RecoveryServices/Vaults/read",
        "Microsoft.RedHatOpenShift/openShiftClusters/read",
        "Microsoft.Resources/Resources/read",
        "Microsoft.Resources/subscriptions/providers/read",
        "Microsoft.Resources/subscriptions/read",
        "Microsoft.Resources/subscriptions/resourceGroups/read",
        "Microsoft.Resources/subscriptions/resourceGroups/write",
        "Microsoft.SaaS/applications/read",
        "Microsoft.Security/advancedThreatProtectionSettings/read",
        "Microsoft.Security/autoProvisioningSettings/read",
        "Microsoft.Security/automations/read",
        "Microsoft.Security/iotSecuritySolutions/read",
        "Microsoft.Security/locations/read",
        "Microsoft.Security/pricings/read",
        "Microsoft.Security/secureScores/read",
        "Microsoft.Security/securityContacts/read",
        "Microsoft.Security/settings/read",
        "Microsoft.Security/workspaceSettings/read",
        "Microsoft.ServiceBus/namespaces/authorizationRules/read",
        "Microsoft.ServiceBus/namespaces/networkrulesets/read",
        "Microsoft.ServiceBus/namespaces/privateEndpointConnections/read",
        "Microsoft.ServiceBus/namespaces/providers/Microsoft.Insights/diagnosticSettings/read",
        "Microsoft.ServiceBus/namespaces/queues/read",
        "Microsoft.ServiceBus/namespaces/read",
        "Microsoft.ServiceBus/namespaces/topics/read",
        "Microsoft.ServiceBus/namespaces/topics/subscriptions/read",
        "Microsoft.ServiceFabric/clusters/read",
        "Microsoft.SignalRService/SignalR/read",
        "Microsoft.SignalRService/WebPubSub/read",
        "Microsoft.Solutions/applications/read",
        "Microsoft.Sql/managedInstances/read",
        "Microsoft.Sql/servers/administrators/read",
        "Microsoft.Sql/servers/auditingSettings/read",
        "Microsoft.Sql/servers/databases/auditingSettings/read",
        "Microsoft.Sql/servers/databases/read",
        "Microsoft.Sql/servers/databases/securityAlertPolicies/read",
        "Microsoft.Sql/servers/databases/transparentDataEncryption/read",
        "Microsoft.Sql/servers/encryptionProtector/read",
        "Microsoft.Sql/servers/firewallRules/read",
        "Microsoft.Sql/servers/read",
        "Microsoft.Sql/servers/securityAlertPolicies/read",
        "Microsoft.Sql/servers/vulnerabilityAssessments/read",
        "Microsoft.Storage/storageAccounts/blobServices/read",
        "Microsoft.Storage/storageAccounts/fileServices/read",
        "Microsoft.Storage/storageAccounts/fileServices/shares/read",
        "Microsoft.Storage/storageAccounts/listKeys/action",
        "Microsoft.Storage/storageAccounts/providers/Microsoft.Insights/diagnosticSettings/read",
        "Microsoft.Storage/storageAccounts/queueServices/read",
        "Microsoft.Storage/storageAccounts/read",
        "Microsoft.Storage/storageAccounts/tableServices/read",
        "Microsoft.StorageCache/Subscription/caches/read",
        "Microsoft.StorageCache/caches/read",
        "Microsoft.StorageMover/storageMovers/read",
        "Microsoft.StorageSync/storageSyncServices/privateLinkResources/read",
        "Microsoft.StorageSync/storageSyncServices/read",
        "Microsoft.StreamAnalytics/clusters/Read",
        "Microsoft.StreamAnalytics/streamingjobs/Read",
        "Microsoft.Subscription/Policies/default/read",
        "Microsoft.Synapse/privateLinkHubs/privateLinkResources/read",
        "Microsoft.Synapse/privateLinkHubs/read",
        "Microsoft.Synapse/workspaces/privateLinkResources/read",
        "Microsoft.Synapse/workspaces/read",
        "Microsoft.Synapse/workspaces/sparkConfigurations/read",
        "Microsoft.TestBase/testBaseAccounts/read",
        "Microsoft.TimeSeriesInsights/environments/read",
        "Microsoft.VideoIndexer/accounts/read",
        "Microsoft.VisualStudio/Account/Read",
        "Microsoft.Web/certificates/read",
        "Microsoft.Web/customApis/read",
        "Microsoft.Web/hostingEnvironments/Read",
        "Microsoft.Web/serverfarms/Read",
        "Microsoft.Web/sites/Read",
        "Microsoft.Web/sites/config/read",
        "Microsoft.Web/sites/read",
        "Microsoft.Web/sites/slots/Read",
        "Microsoft.Web/staticSites/Read",
        "Microsoft.Workloads/monitors/read",
        "Microsoft.classicCompute/domainNames/read",
        "microsoft.app/containerapps/read",
        "microsoft.network/virtualnetworkgateways/connections/read",
        "microsoft.web/serverfarms/sites/read"
      ],
      "type": "list"
    },
    "cloud_environment": {
      "default": "public",
      "type": "string"
    },
    "application_password_expiration": {
      "default": "8760h",
      "type": "string"
    }
  },
  "terraform": {
    "required_providers": {
      "random": "=3.1.0",
      "azuread": "=2.28.1",
      "time": "=0.7.0",
      "azurerm": "=3.24.0"
    }
  }
}